SET TERM ^ ;
CREATE PROCEDURE MP_ROLES_INSERT (
    SITEID Integer,
    ROLENAME Varchar(50),
    DISPLAYNAME Varchar(50),
    SITEGUID Char(36),
    ROLEGUID Char(36) )
RETURNS (
    ROLEID Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^


SET TERM ^ ;
CREATE PROCEDURE MP_SCHEMASCRIPTHISTORY_INSERT (
    APPLICATIONID Char(36),
    SCRIPTFILE Varchar(255),
    "RUNTIME" Timestamp,
    ERROROCCURRED Smallint,
    ERRORMESSAGE Blob sub_type 1,
    SCRIPTBODY Blob sub_type 1 )
RETURNS (
    ID Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE MP_SITES_INSERT (
    SITEGUID Char(36),
    SITENAME Varchar(255),
    SKIN Varchar(100),
    LOGO Varchar(50),
    ICON Varchar(50),
    ALLOWUSERSKINS Smallint,
    ALLOWPAGESKINS Smallint,
    ALLOWHIDEMENUONPAGES Smallint,
    ALLOWNEWREGISTRATION Smallint,
    USESECUREREGISTRATION Smallint,
    USESSLONALLPAGES Smallint,
    DEFAULTPAGEKEYWORDS Varchar(255),
    DEFAULTPAGEDESCRIPTION Varchar(255),
    DEFAULTPAGEENCODING Varchar(255),
    DEFAULTADDITIONALMETATAGS Varchar(255),
    ISSERVERADMINSITE Smallint,
    USELDAPAUTH Smallint,
    AUTOCREATELDAPUSERONFIRSTLOGIN Smallint,
    LDAPSERVER Varchar(255),
    LDAPPORT Integer,
    LDAPDOMAIN Varchar(255),
    LDAPROOTDN Varchar(255),
    LDAPUSERDNKEY Varchar(10),
    REALLYDELETEUSERS Smallint,
    USEEMAILFORLOGIN Smallint,
    ALLOWUSERFULLNAMECHANGE Smallint,
    EDITORSKIN Varchar(50),
    DEFAULTFRIENDLYURLPATTERNENUM Varchar(50),
    ALLOWPASSWORDRETRIEVAL Smallint,
    ALLOWPASSWORDRESET Smallint,
    REQUIRESQUESTIONANDANSWER Smallint,
    MAXINVALIDPASSWORDATTEMPTS Integer,
    PASSWORDATTEMPTWINDOWMINUTES Integer,
    REQUIRESUNIQUEEMAIL Smallint,
    PASSWORDFORMAT Integer,
    MINREQUIREDPASSWORDLENGTH Integer,
    MINREQNONALPHACHARS Integer,
    PWDSTRENGTHREGEX Blob sub_type 1,
    DEFAULTEMAILFROMADDRESS Varchar(100),
    ENABLEMYPAGEFEATURE Smallint,
    EDITORPROVIDER Varchar(255),
    DATEPICKERPROVIDER Varchar(255),
    CAPTCHAPROVIDER Varchar(255),
    RECAPTCHAPRIVATEKEY Varchar(255),
    RECAPTCHAPUBLICKEY Varchar(255),
    WORDPRESSAPIKEY Varchar(255),
    WINDOWSLIVEAPPID Varchar(255),
    WINDOWSLIVEKEY Varchar(255),
    ALLOWOPENIDAUTH Smallint,
    ALLOWWINDOWSLIVEAUTH Smallint,
    GMAPAPIKEY Varchar(255),
    APIKEYEXTRA1 Varchar(255),
    APIKEYEXTRA2 Varchar(255),
    APIKEYEXTRA3 Varchar(255),
    APIKEYEXTRA4 Varchar(255),
    APIKEYEXTRA5 Varchar(255) )
RETURNS (
    SITEID Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE MP_USERROLES_INSERT (
    USERID Integer,
    ROLEID Integer,
    USERGUID Char(36),
    ROLEGUID Char(36) )
RETURNS (
    ID Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE MP_USERS_INSERT (
    SITEID Integer,
    NAME Varchar(100),
    LOGINNAME Varchar(50),
    EMAIL Varchar(100),
    LOWEREDEMAIL Varchar(100),
    "PASSWORD" Varchar(128),
    PASSWORDQUESTION Varchar(255),
    PASSWORDANSWER Varchar(255),
    GENDER Char(10),
    PROFILEAPPROVED Smallint,
    REGISTERCONFIRMGUID Char(36),
    APPROVEDFORFORUMS Smallint,
    TRUSTED Smallint,
    DISPLAYINMEMBERLIST Smallint,
    WEBSITEURL Varchar(100),
    COUNTRY Varchar(100),
    STATE Varchar(100),
    OCCUPATION Varchar(100),
    INTERESTS Varchar(100),
    MSN Varchar(50),
    YAHOO Varchar(50),
    AIM Varchar(50),
    ICQ Varchar(50),
    TOTALPOSTS Integer,
    AVATARURL Varchar(255),
    TIMEOFFSETHOURS Integer,
    SIGNATURE Varchar(255),
    DATECREATED Timestamp,
    USERGUID Char(36),
    SKIN Varchar(100),
    ISDELETED Smallint,
    FAILEDPASSWORDATTEMPTCOUNT Integer,
    FAILEDPWDANSWERATTEMPTCOUNT Integer,
    ISLOCKEDOUT Smallint,
    MOBILEPIN Varchar(16),
    PASSWORDSALT Varchar(128),
    "COMMENT" Blob sub_type 1,
    SITEGUID Char(36) )
RETURNS (
    USERID Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^
