
CREATE TABLE MP_SCHEMAVERSION
(
  APPLICATIONID Varchar(36) NOT NULL,
  APPLICATIONNAME Varchar(255) NOT NULL,
  MAJOR Integer NOT NULL,
  MINOR Integer NOT NULL,
  BUILD Integer NOT NULL,
  REVISION Integer NOT NULL,
  PRIMARY KEY (APPLICATIONID)
);
