
CREATE TABLE MP_CURRENCY
(
  GUID Varchar(36) NOT NULL,
  TITLE Varchar(50) NOT NULL,
  CODE Char(3) NOT NULL,
  SYMBOLLEFT Varchar(15),
  SYMBOLRIGHT Varchar(15),
  DECIMALPOINTCHAR Char(1),
  THOUSANDSPOINTCHAR Char(1),
  DECIMALPLACES Char(1),
  "Value" Integer,
  LASTMODIFIED Timestamp,
  CREATED Timestamp NOT NULL,
  PRIMARY KEY (GUID)
);


CREATE TABLE MP_GEOCOUNTRY
(
  GUID Varchar(36) NOT NULL,
  NAME Varchar(255) NOT NULL,
  ISOCODE2 Char(2) NOT NULL,
  ISOCODE3 Char(3) NOT NULL,
  PRIMARY KEY (GUID)
);
CREATE TABLE MP_GEOZONE
(
  GUID Varchar(36) NOT NULL,
  COUNTRYGUID Varchar(36) NOT NULL,
  NAME Varchar(255) NOT NULL,
  CODE Varchar(255) NOT NULL,
  PRIMARY KEY (GUID)
);


CREATE TABLE MP_LANGUAGE
(
  GUID Varchar(36) NOT NULL,
  NAME Varchar(255) NOT NULL,
  CODE Char(2) NOT NULL,
  "Sort" Integer NOT NULL,
  PRIMARY KEY (GUID)
);


CREATE TABLE MP_ROLES
(
  ROLEID Integer NOT NULL,
  SITEID Integer NOT NULL,
  ROLENAME Varchar(50) NOT NULL,
  DISPLAYNAME Varchar(50),
  SITEGUID Varchar(36),
  ROLEGUID Varchar(36),
  PRIMARY KEY (ROLEID)
);


CREATE TABLE MP_SITEFOLDERS
(
  GUID Varchar(36) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  FOLDERNAME Varchar(255) NOT NULL,
  PRIMARY KEY (GUID)
);

CREATE TABLE MP_SITEHOSTS
(
  HOSTID Integer NOT NULL,
  SITEID Integer NOT NULL,
  HOSTNAME Varchar(255) NOT NULL,
  SITEGUID Varchar(36),
  PRIMARY KEY (HOSTID)
);


CREATE TABLE MP_SITES
(
  SITEID Integer NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  SITENAME Varchar(255) NOT NULL,
  SKIN Varchar(100),
  ALLOWNEWREGISTRATION Smallint default 1 NOT NULL,
  USESECUREREGISTRATION Smallint default 0 NOT NULL,
  ISSERVERADMINSITE Smallint default 0 NOT NULL,
  USELDAPAUTH Smallint default 0 NOT NULL,
  AUTOCREATELDAPUSERONFIRSTLOGIN Smallint default 1 NOT NULL,
  LDAPSERVER Varchar(255),
  LDAPPORT Integer default 389 NOT NULL,
  LDAPDOMAIN Varchar(255),
  LDAPROOTDN Varchar(255),
  LDAPUSERDNKEY Varchar(10) NOT NULL,
  REALLYDELETEUSERS Smallint default 1 NOT NULL,
  USEEMAILFORLOGIN Smallint default 1 NOT NULL,
  REQUIRESQUESTIONANDANSWER Smallint default 0 NOT NULL,
  MAXINVALIDPASSWORDATTEMPTS Integer default 5 NOT NULL,
  MINREQUIREDPASSWORDLENGTH Integer default 7 NOT NULL,
  DEFAULTEMAILFROMADDRESS Varchar(100),
  RECAPTCHAPRIVATEKEY Varchar(255),
  RECAPTCHAPUBLICKEY Varchar(255),
  DisableDbAuth SMALLINT ,
  PRIMARY KEY (SITEID)
);

CREATE TABLE MP_SITESETTINGSEX
(
  SITEID Integer NOT NULL,
  KEYNAME Varchar(128) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  KEYVALUE Blob sub_type 1,
  GROUPNAME Varchar(128),
  PRIMARY KEY (SITEID,KEYNAME)
);

CREATE TABLE MP_SITESETTINGSEXDEF
(
  KEYNAME Varchar(128) NOT NULL,
  GROUPNAME Varchar(128),
  DEFAULTVALUE Blob sub_type 1,
  SORTORDER Integer NOT NULL,
  PRIMARY KEY (KEYNAME)
);




CREATE TABLE MP_USERLOCATION
(
  ROWID Varchar(36) NOT NULL,
  USERGUID Varchar(36) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  IPADDRESS Varchar(50) NOT NULL,
  IPADDRESSLONG Numeric(18,0) NOT NULL,
  HOSTNAME Varchar(255),
  LONGITUDE Float NOT NULL,
  LATITUDE Float NOT NULL,
  ISP Varchar(255),
  CONTINENT Varchar(255),
  COUNTRY Varchar(255),
  REGION Varchar(255),
  CITY Varchar(255),
  TIMEZONE Varchar(255),
  CAPTURECOUNT Integer NOT NULL,
  FIRSTCAPTUREUTC Timestamp NOT NULL,
  LASTCAPTUREUTC Timestamp NOT NULL,
  PRIMARY KEY (ROWID)
);


CREATE TABLE MP_USERPROPERTIES
(
  PROPERTYID Varchar(36) NOT NULL,
  USERGUID Varchar(36) NOT NULL,
  PROPERTYNAME Varchar(255),
  PROPERTYVALUESTRING Blob sub_type 1,
  PROPERTYVALUEBINARY Blob sub_type 0,
  LASTUPDATEDDATE Timestamp NOT NULL,
  ISLAZYLOADED Smallint NOT NULL,
  PRIMARY KEY (PROPERTYID)
);

CREATE TABLE MP_USERROLES
(
  ID Integer NOT NULL,
  USERID Integer NOT NULL,
  ROLEID Integer NOT NULL,
  USERGUID Varchar(36),
  ROLEGUID Varchar(36),
  PRIMARY KEY (ID)
);

CREATE TABLE MP_USERS
(
  USERID Integer NOT NULL,
  SITEID Integer NOT NULL,
  NAME Varchar(100) NOT NULL,
  LOGINNAME Varchar(50),
  EMAIL Varchar(100) NOT NULL,
  LOWEREDEMAIL Varchar(100),
  GENDER VarChar(10),
  ACCOUNTAPPROVED Smallint DEFAULT 1 NOT NULL,
  TRUSTED Smallint default 0 NOT NULL,
  DISPLAYINMEMBERLIST Smallint default 1,
  WEBSITEURL Varchar(100),
  COUNTRY Varchar(100),
  STATE Varchar(100),
  AVATARURL Varchar(255),
  SIGNATURE Varchar(255),
  DATECREATED Timestamp NOT NULL,
  USERGUID Varchar(36),
  ISDELETED Smallint default 0 NOT NULL,
  LASTLOGINDATE Timestamp,
  LASTPASSWORDCHANGEDDATE Timestamp,
  FAILEDPASSWORDATTEMPTCOUNT Integer default 0 NOT NULL,
  ISLOCKEDOUT Smallint default 0 NOT NULL NOT NULL,
  "COMMENT" Blob sub_type 1,
  SITEGUID Varchar(36),
  FIRSTNAME varchar(100),
  LASTNAME varchar(100),
  MUSTCHANGEPWD integer default 0 NOT NULL,
  TIMEZONEID varchar(32),
  NEWEMAIL varchar(100),
  ROLESCHANGED integer default 0 NOT NULL,
  AUTHORBIO blob sub_type 1,
  DATEOFBIRTH timestamp,
  EMAILCONFIRMED integer DEFAULT 1 NOT NULL,
  PASSWORDHASH blob sub_type 1,
  SECURITYSTAMP blob sub_type 1,
  PHONENUMBER varchar(50),
  PHONENUMBERCONFIRMED integer DEFAULT 0 NOT NULL,
  TWOFACTORENABLED integer DEFAULT 0 NOT NULL,
  LOCKOUTENDDATEUTC timestamp,
  PRIMARY KEY (USERID)
);


CREATE TABLE MP_USERCLAIMS
(
  ID integer NOT NULL,
  USERID varchar(128) NOT NULL,
  CLAIMTYPE blob sub_type 1,
  CLAIMVALUE blob sub_type 1,
  CONSTRAINT INTEG_643 PRIMARY KEY (ID)
);

CREATE TABLE MP_USERLOGINS
(
  LOGINPROVIDER varchar(128) NOT NULL,
  PROVIDERKEY varchar(128) NOT NULL,
  USERID varchar(128) NOT NULL
);

