// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cloudscribe.Core.IdentityServer.EFCore.PostgreSql;

namespace cloudscribe.Core.IdentityServer.EFCore.PostgreSql.Migrations.PersistedGrantDb
{
    [DbContext(typeof(PersistedGrantDbContext))]
    [Migration("20181008115259_cloudscribe-idserver-grants-initial")]
    partial class cloudscribeidservergrantsinitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("cloudscribe.Core.IdentityServer.EFCore.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnName("key")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasMaxLength(50);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnName("client_id")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("creation_time");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnName("data");

                    b.Property<DateTime>("Expiration")
                        .HasColumnName("expiration");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnName("site_id")
                        .HasMaxLength(36);

                    b.Property<string>("SubjectId")
                        .HasColumnName("subject_id")
                        .HasMaxLength(200);

                    b.HasKey("Key", "Type")
                        .HasName("pk_csids_persisted_grants");

                    b.HasIndex("SiteId")
                        .HasName("ix_csids_persisted_grants_site_id");

                    b.HasIndex("SubjectId")
                        .HasName("ix_csids_persisted_grants_subject_id");

                    b.HasIndex("SubjectId", "ClientId")
                        .HasName("ix_csids_persisted_grants_subject_id_client_id");

                    b.HasIndex("SubjectId", "ClientId", "Type")
                        .HasName("ix_csids_persisted_grants_subject_id_client_id_type");

                    b.ToTable("csids_persisted_grants");
                });
#pragma warning restore 612, 618
        }
    }
}
