SET TERM ^ ;
CREATE TRIGGER MP_BANNEDIPADDRESSES_BI FOR MP_BANNEDIPADDRESSES ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.RowID  IS NULL) THEN
 NEW.RowID  = NEXT VALUE FOR mp_BannedIPAddresses_seq;
END^
SET TERM ; ^

SET TERM ^ ;
CREATE TRIGGER MP_INDEXINGQUEUE_BI FOR MP_INDEXINGQUEUE ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.RowId  IS NULL) THEN
 NEW.RowId  = NEXT VALUE FOR mp_IndexingQueue_seq;
END^
SET TERM ; ^


