
CREATE TABLE MP_BANNEDIPADDRESSES
(
  ROWID Integer NOT NULL,
  BANNEDIP Varchar(50) NOT NULL,
  BANNEDUTC Timestamp NOT NULL,
  BANNEDREASON Varchar(255),
  PRIMARY KEY (ROWID)
);


CREATE TABLE MP_CURRENCY
(
  GUID Varchar(36) NOT NULL,
  TITLE Varchar(50) NOT NULL,
  CODE Char(3) NOT NULL,
  SYMBOLLEFT Varchar(15),
  SYMBOLRIGHT Varchar(15),
  DECIMALPOINTCHAR Char(1),
  THOUSANDSPOINTCHAR Char(1),
  DECIMALPLACES Char(1),
  "Value" Integer,
  LASTMODIFIED Timestamp,
  CREATED Timestamp NOT NULL,
  PRIMARY KEY (GUID)
);


CREATE TABLE MP_GEOCOUNTRY
(
  GUID Varchar(36) NOT NULL,
  NAME Varchar(255) NOT NULL,
  ISOCODE2 Char(2) NOT NULL,
  ISOCODE3 Char(3) NOT NULL,
  PRIMARY KEY (GUID)
);
CREATE TABLE MP_GEOZONE
(
  GUID Varchar(36) NOT NULL,
  COUNTRYGUID Varchar(36) NOT NULL,
  NAME Varchar(255) NOT NULL,
  CODE Varchar(255) NOT NULL,
  PRIMARY KEY (GUID)
);

CREATE TABLE MP_INDEXINGQUEUE
(
  ROWID Numeric(18,0) NOT NULL,
  INDEXPATH Varchar(255) NOT NULL,
  SERIALIZEDITEM Blob sub_type 1 NOT NULL,
  ITEMKEY Varchar(255) NOT NULL,
  REMOVEONLY Smallint NOT NULL,
  SiteID INTEGER NOT NULL,
  PRIMARY KEY (ROWID)
);


CREATE TABLE MP_LANGUAGE
(
  GUID Varchar(36) NOT NULL,
  NAME Varchar(255) NOT NULL,
  CODE Char(2) NOT NULL,
  "Sort" Integer NOT NULL,
  PRIMARY KEY (GUID)
);

CREATE TABLE MP_REDIRECTLIST
(
  ROWGUID Varchar(36) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  SITEID Integer NOT NULL,
  OLDURL Varchar(255) NOT NULL,
  NEWURL Varchar(255) NOT NULL,
  CREATEDUTC Timestamp NOT NULL,
  EXPIREUTC Timestamp NOT NULL,
  PRIMARY KEY (ROWGUID)
);

CREATE TABLE MP_ROLES
(
  ROLEID Integer NOT NULL,
  SITEID Integer NOT NULL,
  ROLENAME Varchar(50) NOT NULL,
  DISPLAYNAME Varchar(50),
  SITEGUID Varchar(36),
  ROLEGUID Varchar(36),
  PRIMARY KEY (ROLEID)
);

CREATE TABLE MP_SCHEMASCRIPTHISTORY
(
  ID Integer NOT NULL,
  APPLICATIONID Varchar(36) NOT NULL,
  SCRIPTFILE Varchar(255) NOT NULL,
  "RUNTIME" Timestamp NOT NULL,
  ERROROCCURRED Smallint NOT NULL,
  ERRORMESSAGE Blob sub_type 1,
  SCRIPTBODY Blob sub_type 1,
  PRIMARY KEY (ID)
);

CREATE TABLE MP_SCHEMAVERSION
(
  APPLICATIONID Varchar(36) NOT NULL,
  APPLICATIONNAME Varchar(255) NOT NULL,
  MAJOR Integer NOT NULL,
  MINOR Integer NOT NULL,
  BUILD Integer NOT NULL,
  REVISION Integer NOT NULL,
  PRIMARY KEY (APPLICATIONID)
);

CREATE TABLE MP_SITEFOLDERS
(
  GUID Varchar(36) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  FOLDERNAME Varchar(255) NOT NULL,
  PRIMARY KEY (GUID)
);

CREATE TABLE MP_SITEHOSTS
(
  HOSTID Integer NOT NULL,
  SITEID Integer NOT NULL,
  HOSTNAME Varchar(255) NOT NULL,
  SITEGUID Varchar(36),
  PRIMARY KEY (HOSTID)
);


CREATE TABLE MP_SITES
(
  SITEID Integer NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  SITEALIAS Varchar(50),
  SITENAME Varchar(255) NOT NULL,
  SKIN Varchar(100),
  LOGO Varchar(50),
  ICON Varchar(50),
  ALLOWUSERSKINS Smallint NOT NULL,
  ALLOWPAGESKINS Smallint NOT NULL,
  ALLOWHIDEMENUONPAGES Smallint NOT NULL,
  ALLOWNEWREGISTRATION Smallint NOT NULL,
  USESECUREREGISTRATION Smallint NOT NULL,
  USESSLONALLPAGES Smallint NOT NULL,
  DEFAULTPAGEKEYWORDS Varchar(255),
  DEFAULTPAGEDESCRIPTION Varchar(255),
  DEFAULTPAGEENCODING Varchar(255),
  DEFAULTADDITIONALMETATAGS Varchar(255),
  ISSERVERADMINSITE Smallint NOT NULL,
  USELDAPAUTH Smallint NOT NULL,
  AUTOCREATELDAPUSERONFIRSTLOGIN Smallint NOT NULL,
  LDAPSERVER Varchar(255),
  LDAPPORT Integer NOT NULL,
  LDAPDOMAIN Varchar(255),
  LDAPROOTDN Varchar(255),
  LDAPUSERDNKEY Varchar(10) NOT NULL,
  REALLYDELETEUSERS Smallint NOT NULL,
  USEEMAILFORLOGIN Smallint NOT NULL,
  ALLOWUSERFULLNAMECHANGE Smallint NOT NULL,
  EDITORSKIN Varchar(50) NOT NULL,
  DEFAULTFRIENDLYURLPATTERNENUM Varchar(50) NOT NULL,
  ALLOWPASSWORDRETRIEVAL Smallint NOT NULL,
  ALLOWPASSWORDRESET Smallint NOT NULL,
  REQUIRESQUESTIONANDANSWER Smallint NOT NULL,
  MAXINVALIDPASSWORDATTEMPTS Integer NOT NULL,
  PASSWORDATTEMPTWINDOWMINUTES Integer NOT NULL,
  REQUIRESUNIQUEEMAIL Smallint NOT NULL,
  PASSWORDFORMAT Integer NOT NULL,
  MINREQUIREDPASSWORDLENGTH Integer NOT NULL,
  MINREQNONALPHACHARS Integer NOT NULL,
  PWDSTRENGTHREGEX Blob sub_type 1,
  DEFAULTEMAILFROMADDRESS Varchar(100),
  ENABLEMYPAGEFEATURE Smallint NOT NULL,
  EDITORPROVIDER Varchar(255),
  CAPTCHAPROVIDER Varchar(255),
  DATEPICKERPROVIDER Varchar(255),
  RECAPTCHAPRIVATEKEY Varchar(255),
  RECAPTCHAPUBLICKEY Varchar(255),
  WORDPRESSAPIKEY Varchar(255),
  WINDOWSLIVEAPPID Varchar(255),
  WINDOWSLIVEKEY Varchar(255),
  ALLOWOPENIDAUTH Smallint,
  ALLOWWINDOWSLIVEAUTH Smallint,
  GMAPAPIKEY Varchar(255),
  APIKEYEXTRA1 Varchar(255),
  APIKEYEXTRA2 Varchar(255),
  APIKEYEXTRA3 Varchar(255),
  APIKEYEXTRA4 Varchar(255),
  APIKEYEXTRA5 Varchar(255),
  DisableDbAuth SMALLINT ,
  PRIMARY KEY (SITEID)
);

CREATE TABLE MP_SITESETTINGSEX
(
  SITEID Integer NOT NULL,
  KEYNAME Varchar(128) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  KEYVALUE Blob sub_type 1,
  GROUPNAME Varchar(128),
  PRIMARY KEY (SITEID,KEYNAME)
);

CREATE TABLE MP_SITESETTINGSEXDEF
(
  KEYNAME Varchar(128) NOT NULL,
  GROUPNAME Varchar(128),
  DEFAULTVALUE Blob sub_type 1,
  SORTORDER Integer NOT NULL,
  PRIMARY KEY (KEYNAME)
);

CREATE TABLE MP_TASKQUEUE
(
  GUID Varchar(36) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  QUEUEDBY Varchar(36) NOT NULL,
  TASKNAME Varchar(255) NOT NULL,
  NOTIFYONCOMPLETION Smallint NOT NULL,
  NOTIFICATIONTOEMAIL Varchar(255),
  NOTIFICATIONFROMEMAIL Varchar(255),
  NOTIFICATIONSUBJECT Varchar(255),
  TASKCOMPLETEMESSAGE Blob sub_type 1,
  NOTIFICATIONSENTUTC Timestamp,
  CANSTOP Smallint NOT NULL,
  CANRESUME Smallint NOT NULL,
  UPDATEFREQUENCY Integer NOT NULL,
  QUEUEDUTC Timestamp NOT NULL,
  STARTUTC Timestamp,
  COMPLETEUTC Timestamp,
  LASTSTATUSUPDATEUTC Timestamp,
  COMPLETERATIO Float NOT NULL,
  STATUS Varchar(255),
  SERIALIZEDTASKOBJECT Blob sub_type 1,
  SERIALIZEDTASKTYPE Varchar(255),
  PRIMARY KEY (GUID)
);


CREATE TABLE MP_USERLOCATION
(
  ROWID Varchar(36) NOT NULL,
  USERGUID Varchar(36) NOT NULL,
  SITEGUID Varchar(36) NOT NULL,
  IPADDRESS Varchar(50) NOT NULL,
  IPADDRESSLONG Numeric(18,0) NOT NULL,
  HOSTNAME Varchar(255),
  LONGITUDE Float NOT NULL,
  LATITUDE Float NOT NULL,
  ISP Varchar(255),
  CONTINENT Varchar(255),
  COUNTRY Varchar(255),
  REGION Varchar(255),
  CITY Varchar(255),
  TIMEZONE Varchar(255),
  CAPTURECOUNT Integer NOT NULL,
  FIRSTCAPTUREUTC Timestamp NOT NULL,
  LASTCAPTUREUTC Timestamp NOT NULL,
  PRIMARY KEY (ROWID)
);


CREATE TABLE MP_USERPROPERTIES
(
  PROPERTYID Varchar(36) NOT NULL,
  USERGUID Varchar(36) NOT NULL,
  PROPERTYNAME Varchar(255),
  PROPERTYVALUESTRING Blob sub_type 1,
  PROPERTYVALUEBINARY Blob sub_type 0,
  LASTUPDATEDDATE Timestamp NOT NULL,
  ISLAZYLOADED Smallint NOT NULL,
  PRIMARY KEY (PROPERTYID)
);

CREATE TABLE MP_USERROLES
(
  ID Integer NOT NULL,
  USERID Integer NOT NULL,
  ROLEID Integer NOT NULL,
  USERGUID Varchar(36),
  ROLEGUID Varchar(36),
  PRIMARY KEY (ID)
);

CREATE TABLE MP_USERS
(
  USERID Integer NOT NULL,
  SITEID Integer NOT NULL,
  NAME Varchar(100) NOT NULL,
  LOGINNAME Varchar(50),
  EMAIL Varchar(100) NOT NULL,
  LOWEREDEMAIL Varchar(100),
  "PASSWORD" Varchar(128) NOT NULL,
  PASSWORDQUESTION Varchar(255),
  PASSWORDANSWER Varchar(255),
  GENDER Char(10),
  PROFILEAPPROVED Smallint NOT NULL,
  REGISTERCONFIRMGUID Varchar(36),
  APPROVEDFORFORUMS Smallint NOT NULL,
  TRUSTED Smallint NOT NULL,
  DISPLAYINMEMBERLIST Smallint,
  WEBSITEURL Varchar(100),
  COUNTRY Varchar(100),
  STATE Varchar(100),
  OCCUPATION Varchar(100),
  INTERESTS Varchar(100),
  MSN Varchar(50),
  YAHOO Varchar(50),
  AIM Varchar(50),
  ICQ Varchar(50),
  TOTALPOSTS Integer NOT NULL,
  AVATARURL Varchar(255),
  TIMEOFFSETHOURS Integer NOT NULL,
  SIGNATURE Varchar(255),
  DATECREATED Timestamp NOT NULL,
  USERGUID Varchar(36),
  SKIN Varchar(100),
  ISDELETED Smallint NOT NULL,
  LASTACTIVITYDATE Timestamp,
  LASTLOGINDATE Timestamp,
  LASTPASSWORDCHANGEDDATE Timestamp,
  LASTLOCKOUTDATE Timestamp,
  FAILEDPASSWORDATTEMPTCOUNT Integer,
  FAILEDPWDATTEMPTWINDOWSTART Timestamp,
  FAILEDPWDANSWERATTEMPTCOUNT Integer,
  FAILEDPWDANSWERWINDOWSTART Timestamp,
  ISLOCKEDOUT Smallint NOT NULL,
  MOBILEPIN Varchar(16),
  PASSWORDSALT Varchar(128),
  "COMMENT" Blob sub_type 1,
  OPENIDURI Varchar(255),
  WINDOWSLIVEID Varchar(36),
  SITEGUID Varchar(36),
  TOTALREVENUE integer,
  FIRSTNAME varchar(100),
  LASTNAME varchar(100),
  PWD varchar(1000),
  MUSTCHANGEPWD integer,
  TIMEZONEID varchar(32),
  EDITORPREFERENCE varchar(100),
  NEWEMAIL varchar(100),
  EMAILCHANGEGUID char(36),
  PASSWORDRESETGUID char(36),
  ROLESCHANGED integer,
  AUTHORBIO blob sub_type 1,
  DATEOFBIRTH timestamp,
  PWDFORMAT integer DEFAULT 0 NOT NULL,
  EMAILCONFIRMED integer DEFAULT 1 NOT NULL,
  PASSWORDHASH blob sub_type 1,
  SECURITYSTAMP blob sub_type 1,
  PHONENUMBER varchar(50),
  PHONENUMBERCONFIRMED integer DEFAULT 0 NOT NULL,
  TWOFACTORENABLED integer DEFAULT 0 NOT NULL,
  LOCKOUTENDDATEUTC timestamp,
  PRIMARY KEY (USERID)
);

CREATE TABLE MP_SYSTEMLOG
(
  ID integer NOT NULL,
  LOGDATE timestamp NOT NULL,
  IPADDRESS varchar(50),
  CULTURE varchar(10),
  URL blob sub_type 1,
  SHORTURL varchar(255),
  THREAD varchar(255) NOT NULL,
  LOGLEVEL varchar(20) NOT NULL,
  LOGGER varchar(255) NOT NULL,
  "MESSAGE" blob sub_type 1,
  CONSTRAINT INTEG_564 PRIMARY KEY (ID)
);

CREATE TABLE MP_USERCLAIMS
(
  ID integer NOT NULL,
  USERID varchar(128) NOT NULL,
  CLAIMTYPE blob sub_type 1,
  CLAIMVALUE blob sub_type 1,
  CONSTRAINT INTEG_643 PRIMARY KEY (ID)
);

CREATE TABLE MP_USERLOGINS
(
  LOGINPROVIDER varchar(128) NOT NULL,
  PROVIDERKEY varchar(128) NOT NULL,
  USERID varchar(128) NOT NULL
);

